apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-qa
  namespace: qa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc-qa
  resources:
    requests:
      storage: 100Gi