apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-sc-prod
  resources:
    requests:
      storage: 10Gi