apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: qa
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: ghcr.io/baobab-kr/infrastructure-as-code/base-mysql-8.0.25:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: baobab-qa
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: baobab-qa
                  key: db_name
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: mysql-volume-qa
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume-qa
          persistentVolumeClaim:
            claimName: mysql-pvc-qa
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql