apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: prod
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bitnami/mysql:5.7.40
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: baobab-prod-cm
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: baobab-prod-cm
                  key: db_name
            - name : MYSQL_CHARACTER_SET
              valueFrom:
                configMapKeyRef:
                  name: baobab-prod-cm
                  key: mysql_character_set
            - name : MYSQL_COLLATE
              valueFrom:
                configMapKeyRef:
                  name: baobab-prod-cm
                  key: mysql_collate
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: mysql-volume-prod
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume-prod
          persistentVolumeClaim:
            claimName: mysql-pvc-prod
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql