apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: qa
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: ghcr.io/baobab-kr/infrastructure-as-code/base-mysql-8.0.28:v0.1.2
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: baobab-qa
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: baobab-qa
                  key: db_name
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 100m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql